#!/usr/bin/env bash
# Install the Hyprland hotkeys (Ctrl+Alt+R/T/S) and the settings-panel
# window rule -- the Hyprland counterpart to binding GNOME custom shortcuts
# by hand.
#
# Writes ~/.config/hypr/kokoro.lua from linux/kokoro-hyprland.lua.in and adds
# one dofile() line for it to ~/.config/hypr/hyprland.lua (only once; the
# original is backed up first). Needs Hyprland's Lua config. Tested on
# Omarchy 4.0.4 / Hyprland 0.56.2.
#
# Per-user, no root needed. Re-run after moving the folder: the paths are
# baked in at install time from wherever this script lives.

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
HYPR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
DEST="$HYPR/kokoro.lua"
MAIN="$HYPR/hyprland.lua"
LINE="dofile(\"$DEST\")"

if [[ ! -f $MAIN ]]; then
  echo "no $MAIN -- this needs Hyprland's Lua config." >&2
  echo "Bind these by hand instead (see README):" >&2
  for mode in selection clipboard stop; do echo "  $ROOT/read_aloud.sh $mode" >&2; done
  exit 1
fi

sed "s|@ROOT@|$ROOT|g" "$ROOT/linux/kokoro-hyprland.lua.in" > "$DEST"
chmod 644 "$DEST"
echo "installed $DEST"

if grep -qF "$LINE" "$MAIN"; then
  echo "already loaded from $MAIN"
else
  cp "$MAIN" "$MAIN.bak.$(date +%s)"
  printf '\n-- Kokoro read-aloud hotkeys (generated by %s).\n%s\n' \
    "$ROOT/linux/install-hyprland.sh" "$LINE" >> "$MAIN"
  echo "added to $MAIN (backup kept next to it)"
fi

# A bind left over from setting this up by hand would fire as well, so every
# press would POST twice.
others=$(grep -lF "read_aloud.sh" "$HYPR"/*.lua 2>/dev/null | grep -vxF "$DEST" || true)
if [[ -n $others ]]; then
  echo
  echo "WARNING: read_aloud.sh is also bound in:" >&2
  sed 's/^/  /' <<<"$others" >&2
  echo "Remove those binds, or every hotkey press fires twice." >&2
fi

# Hyprland reloads on save anyway; this is for the error check.
if command -v hyprctl >/dev/null && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
  hyprctl reload >/dev/null
  errors=$(hyprctl configerrors | sed '/^[[:space:]]*$/d')
  if [[ -n $errors ]]; then
    echo "Hyprland reports config errors:" >&2
    echo "$errors" >&2
    exit 1
  fi
fi

echo
echo "  Ctrl+Alt+R  read the selection"
echo "  Ctrl+Alt+T  read the clipboard"
echo "  Ctrl+Alt+S  stop"
